name: Run BTC Calculations and Push Results

on:
  schedule:
    # Runs at 2:00 AM UTC daily
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script_calcul_btc.py
      run: |
        python script_calcul_btc.py

    - name: Commit and push changes
      run: |
        git config --local user.email "marius.ortiz@10h11.com"
        git config --local user.name "mariusortiz"
        git add .  # Ajoute tous les fichiers modifiés
        git commit -m "Update Bitcoin prediction data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
