name: Update Kaspa Data

on:
  schedule:
    - cron: '0 1 * * *'  # Exécute le script tous les jours à 01h00 UTC

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pycoingecko pandas boto3

      - name: Run script
        run: python maj_kas.py

      - name: Commit and push the changes
        run: |
          git config --local user.email "marius.ortiz@10h11.com"
          git config --local user.name "mariusortiz"
          git add kas_d.csv
          git commit -m "Update Kaspa data"
          git push
